chords:
    A: ["Δ", "-7", "7"]
    Bb: ["Δ", "-7", "7"]
    B: ["Δ", "-7", "7"]
    C: ["Δ", "-7", "7"]
    Db: ["Δ", "-7", "7"]
    D: ["Δ", "-7", "7"]
    Eb: ["Δ", "-7", "7"]
    E: ["Δ", "-7", "7"]
    F: ["Δ", "-7", "7"]
    Gb: ["Δ",  "7"]
    F#: ["-7"]
    G: ["Δ", "-7", "7"]
    Ab: ["Δ", "-7", "7"]
